/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo;

import javax.swing.JOptionPane;

/**
 *
 * @author liliane_vale
 */
public class Jogo_PapelPedraTesoura extends javax.swing.JFrame {
int ganhadorC=-1;
int ganhadorU=-1;
    /**
     * Creates new form Jogo_PapelPedraTesoura
     */
    public Jogo_PapelPedraTesoura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        pedra = new javax.swing.JRadioButton();
        papel = new javax.swing.JRadioButton();
        tesoura = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pedra, papel ou tesoura?");

        buttonGroup1.add(pedra);
        pedra.setText("Pedra");
        pedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedraActionPerformed(evt);
            }
        });

        buttonGroup1.add(papel);
        papel.setText("Papel");

        buttonGroup1.add(tesoura);
        tesoura.setText("Tesoura");

        jButton1.setText("Jogar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(papel)
                            .addComponent(pedra)
                            .addComponent(tesoura)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jButton1)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(pedra)
                .addGap(18, 18, 18)
                .addComponent(papel)
                .addGap(18, 18, 18)
                .addComponent(tesoura)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pedraActionPerformed

    public static int randInt(int min, int max)
{
java.util.Random rand = new java.util.Random();
int randomNum = rand.nextInt((max - min) + 1) + min;
return randomNum;
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.ganhadorC = randInt(0, 2);
        if(this.ganhadorC==2){
        JOptionPane.showMessageDialog(null, "Computador jogou tesoura");}
        if(this.ganhadorC==1){
        JOptionPane.showMessageDialog(null, "Computador jogou papel");}
        if(this.ganhadorC==0){
        JOptionPane.showMessageDialog(null, "Computador jogou pedra");}
        
        if(pedra.isSelected()){
    if(this.ganhadorC==2){
     JOptionPane.showMessageDialog(null, "Usuario é ganhador!!");
    }
    
    if(this.ganhadorC==0){
     JOptionPane.showMessageDialog(null, "Deu empate!!");
    }
    if(this.ganhadorC==1){
     JOptionPane.showMessageDialog(null, "Computador é ganhador!!");
    }
    //
}
if(papel.isSelected()){
    if(this.ganhadorC==2){
     JOptionPane.showMessageDialog(null, "Computador é ganhador!!");
    }
    
    if(this.ganhadorC==0){
     JOptionPane.showMessageDialog(null, "Usuario é ganhador!!");
    }
    if(this.ganhadorC==1){
     JOptionPane.showMessageDialog(null, "Deu empate!!");
    }
    
    
}

if(tesoura.isSelected()){
if(this.ganhadorC==2){
     JOptionPane.showMessageDialog(null, "Deu empate!!");
    }
    
    if(this.ganhadorC==0){
     JOptionPane.showMessageDialog(null, "Computador é ganhador!!");
    }
    if(this.ganhadorC==1){
     JOptionPane.showMessageDialog(null, "Usuario é ganhador!!");
    }}

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo_PapelPedraTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo_PapelPedraTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo_PapelPedraTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo_PapelPedraTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo_PapelPedraTesoura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton papel;
    private javax.swing.JRadioButton pedra;
    private javax.swing.JRadioButton tesoura;
    // End of variables declaration//GEN-END:variables
}
